version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: movie-api
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
    networks:
      - network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: movie-api
    networks:
      - network
    ports:
      - 8080:8080
    depends_on:
      - "db"

networks:
  network:
    driver: bridge

volumes:
  db_data: