version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: movie-api
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: