spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2-console

